/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.ControllerJogador;
import Controllers.ControllerRoda;
import Controllers.ControllerRodaRoda;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author raphael
 */
public class ViewRodaRoda extends javax.swing.JFrame {

    private final ViewInicial vwInicial;
    private final ArrayList<ControllerJogador> jogadores;
    private final ControllerRodaRoda controllerRodaRoda;


    /**
     * Creates new form ViewRodaRoda
     *
     * @param vwInicial
     * @param configuracoes
     */
    public ViewRodaRoda(ViewInicial vwInicial, JSONObject configuracoes) {
        initComponents();
        this.vwInicial = vwInicial;
        jogadores = new ArrayList<>();
        this.controllerRodaRoda = new ControllerRodaRoda();
        setarValores(configuracoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainContainer = new javax.swing.JPanel();
        containerNorte = new javax.swing.JPanel();
        containerCentral = new javax.swing.JPanel();
        pnRoda = new javax.swing.JPanel();
        pnValor = new javax.swing.JPanel();
        lbValor = new javax.swing.JLabel();
        pnPalavra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        containerSul = new javax.swing.JPanel();
        pnBotoesAcao = new javax.swing.JPanel();
        btnTentarPalavra = new javax.swing.JButton();
        btnTentar = new javax.swing.JButton();
        btnRodar = new javax.swing.JButton();
        pnTxtField = new javax.swing.JPanel();
        txtFldValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        mainContainer.setBackground(new java.awt.Color(158, 158, 158));
        mainContainer.setMinimumSize(new java.awt.Dimension(800, 600));
        mainContainer.setPreferredSize(new java.awt.Dimension(800, 600));
        mainContainer.setLayout(new java.awt.BorderLayout());

        containerNorte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        containerNorte.setMaximumSize(new java.awt.Dimension(800, 200));
        containerNorte.setMinimumSize(new java.awt.Dimension(4, 200));
        containerNorte.setPreferredSize(new java.awt.Dimension(800, 200));
        containerNorte.setLayout(new java.awt.GridLayout(3, 1));
        mainContainer.add(containerNorte, java.awt.BorderLayout.NORTH);

        containerCentral.setBackground(new java.awt.Color(245, 245, 245));
        containerCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        containerCentral.setMaximumSize(new java.awt.Dimension(800, 250));
        containerCentral.setMinimumSize(new java.awt.Dimension(0, 150));
        containerCentral.setPreferredSize(new java.awt.Dimension(800, 200));

        pnValor.setBackground(new java.awt.Color(255, 255, 255));
        pnValor.setEnabled(false);
        pnValor.setPreferredSize(new java.awt.Dimension(70, 30));

        lbValor.setText("jLabel2");
        pnValor.add(lbValor);

        pnRoda.add(pnValor);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        pnPalavra.add(jLabel1);

        javax.swing.GroupLayout containerCentralLayout = new javax.swing.GroupLayout(containerCentral);
        containerCentral.setLayout(containerCentralLayout);
        containerCentralLayout.setHorizontalGroup(
            containerCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRoda, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        containerCentralLayout.setVerticalGroup(
            containerCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCentralLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pnRoda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pnPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        mainContainer.add(containerCentral, java.awt.BorderLayout.CENTER);

        containerSul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        containerSul.setMinimumSize(new java.awt.Dimension(200, 80));
        containerSul.setPreferredSize(new java.awt.Dimension(800, 100));
        containerSul.setLayout(new java.awt.BorderLayout());

        pnBotoesAcao.setPreferredSize(new java.awt.Dimension(800, 40));
        pnBotoesAcao.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        btnTentarPalavra.setText("Tentar Palavra");
        btnTentarPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarPalavraActionPerformed(evt);
            }
        });
        pnBotoesAcao.add(btnTentarPalavra);

        btnTentar.setText("Tentar");
        pnBotoesAcao.add(btnTentar);

        btnRodar.setText("Rodar");
        btnRodar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodarActionPerformed(evt);
            }
        });
        pnBotoesAcao.add(btnRodar);

        containerSul.add(pnBotoesAcao, java.awt.BorderLayout.PAGE_START);

        pnTxtField.setMinimumSize(new java.awt.Dimension(70, 100));
        pnTxtField.setPreferredSize(new java.awt.Dimension(800, 40));

        txtFldValor.setText("jTextField1");
        txtFldValor.setMinimumSize(new java.awt.Dimension(60, 19));
        txtFldValor.setPreferredSize(new java.awt.Dimension(240, 25));
        txtFldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldValorActionPerformed(evt);
            }
        });
        pnTxtField.add(txtFldValor);

        containerSul.add(pnTxtField, java.awt.BorderLayout.PAGE_END);

        mainContainer.add(containerSul, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTentarPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTentarPalavraActionPerformed

    private void btnRodarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRodarActionPerformed

    private void txtFldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldValorActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setSize(900, 700);
    }//GEN-LAST:event_formComponentShown

    private void setarValores(JSONObject configuracoes) {
        pnValor.setVisible(false);
        for (int i = 1; i <= (int) configuracoes.get("numeroJogadores"); i++) {
            String nome = JOptionPane.showInputDialog("Qual o nome do Jogador " + i);
            ControllerJogador jogador = new ControllerJogador(controllerRodaRoda);
            if ("".equals(nome) && nome == null) {
                nome = "Jogador " + i;
            }
            jogador.set("nome", nome);
            jogador.set("pontos", 0);
            jogador.atualizarDados();
            jogadores.add(jogador);
            ContainerJogador ctJogador = new ContainerJogador(nome);
            //if(i == 1)
              //  containerNorte.add(ctJogador);
            //if(i == 2)
              //  containerNorte.add(ctJogador);
            //if(i == 3)
                containerNorte.add(ctJogador);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRodar;
    private javax.swing.JButton btnTentar;
    private javax.swing.JButton btnTentarPalavra;
    private javax.swing.JPanel containerCentral;
    private javax.swing.JPanel containerNorte;
    private javax.swing.JPanel containerSul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbValor;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel pnBotoesAcao;
    private javax.swing.JPanel pnPalavra;
    private javax.swing.JPanel pnRoda;
    private javax.swing.JPanel pnTxtField;
    private javax.swing.JPanel pnValor;
    private javax.swing.JTextField txtFldValor;
    // End of variables declaration//GEN-END:variables
}
