/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.ControllerAbstrato;
import Controllers.ControllerConfiguracao;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.json.simple.JSONObject;

/**
 *
 * @author raphael
 */
public class ViewConfiguracoes extends javax.swing.JPanel implements View {

    ControllerConfiguracao controller;

    /**
     * Creates new form ViewConfiguracoes
     */
    public ViewConfiguracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        pnHeader = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        pnCentral = new javax.swing.JPanel();
        pnNumeroJogadores = new javax.swing.JPanel();
        lbNumeroJogadores = new javax.swing.JLabel();
        cbNumeroJogadores = new javax.swing.JComboBox<>();
        pnNumeroEtapas = new javax.swing.JPanel();
        lbNumeroEtapas = new javax.swing.JLabel();
        cbNumeroEtapas = new javax.swing.JComboBox<>();
        pnNumeroPalavras = new javax.swing.JPanel();
        lbNumeroPalavras = new javax.swing.JLabel();
        cbNumeroPalavras = new javax.swing.JComboBox<>();
        pnDiferentesCategorias = new javax.swing.JPanel();
        chbDiferentesCategorias = new javax.swing.JCheckBox();
        pnBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lbHeader.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        lbHeader.setText("Configurações");
        lbHeader.setAlignmentX(0.5F);

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbHeader)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnHeader);

        pnCentral.setLayout(new java.awt.GridLayout(4, 1));

        lbNumeroJogadores.setText("Número de Jogadores");
        pnNumeroJogadores.add(lbNumeroJogadores);

        cbNumeroJogadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Número Jogador" }));
        cbNumeroJogadores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbNumeroJogadoresComponentShown(evt);
            }
        });
        cbNumeroJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumeroJogadoresActionPerformed(evt);
            }
        });
        pnNumeroJogadores.add(cbNumeroJogadores);

        pnCentral.add(pnNumeroJogadores);

        lbNumeroEtapas.setText("Número de Etapas");
        pnNumeroEtapas.add(lbNumeroEtapas);

        cbNumeroEtapas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Número Etapas" }));
        cbNumeroEtapas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbNumeroEtapasComponentShown(evt);
            }
        });
        pnNumeroEtapas.add(cbNumeroEtapas);

        pnCentral.add(pnNumeroEtapas);

        lbNumeroPalavras.setText("Número de Palavras");
        pnNumeroPalavras.add(lbNumeroPalavras);

        cbNumeroPalavras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Número Palavras" }));
        cbNumeroPalavras.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbNumeroPalavrasComponentShown(evt);
            }
        });
        pnNumeroPalavras.add(cbNumeroPalavras);

        pnCentral.add(pnNumeroPalavras);

        chbDiferentesCategorias.setText("Diferentes Categorias");
        pnDiferentesCategorias.add(chbDiferentesCategorias);

        pnCentral.add(pnDiferentesCategorias);

        add(pnCentral);

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        pnBotoes.add(btnSalvar);

        btnFechar.setText("Fechar");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });
        pnBotoes.add(btnFechar);

        add(pnBotoes);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNumeroJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumeroJogadoresActionPerformed

    }//GEN-LAST:event_cbNumeroJogadoresActionPerformed

    private void cbNumeroJogadoresComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbNumeroJogadoresComponentShown
        System.out.println("View.ViewConfiguracoes.cbNumeroJogadoresComponentShown()");
        for (Integer i = 1; i <= (int) controller.get("limiteJogadores"); i++) {
            cbNumeroJogadores.addItem(i.toString());
        }
    }//GEN-LAST:event_cbNumeroJogadoresComponentShown

    private void cbNumeroEtapasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbNumeroEtapasComponentShown
        System.out.println("View.ViewConfiguracoes.cbNumeroEtapasComponentShown()");
        for (Integer i = 1; i <= (int) controller.get("limiteEtapas"); i++) {
            cbNumeroEtapas.addItem(i.toString());
        }
    }//GEN-LAST:event_cbNumeroEtapasComponentShown

    private void cbNumeroPalavrasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbNumeroPalavrasComponentShown
        System.out.println("View.ViewConfiguracoes.cbNumeroPalavrasComponentShown()");
        for (Integer i = 1; i <= (int) controller.get("limitePalavras"); i++) {
            cbNumeroPalavras.addItem(i.toString());
        }
    }//GEN-LAST:event_cbNumeroPalavrasComponentShown

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        JSONObject dados = verificarDados();
        if(dados.get("erro") != null){
            JOptionPane.showMessageDialog(new JOptionPane(), "Preencha os campos obrigatorios");
        }
        else{
            controller.carregarDados(dados);
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.setVisible(false);
            }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.setVisible(false);
    }//GEN-LAST:event_btnFecharMouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden
    private JSONObject verificarDados() {
        JSONObject dados = new JSONObject();

        if (cbNumeroEtapas.getSelectedItem().toString().indexOf("Selecione") < 0) {
            dados.put("numeroEtapas", Integer.parseInt((String) cbNumeroEtapas.getSelectedItem()));
        } else {
            dados.put("erro", true);
        }
        if (cbNumeroPalavras.getSelectedItem().toString().indexOf("Selecione") < 0) {
            dados.put("numeroPalavras", Integer.parseInt((String) cbNumeroPalavras.getSelectedItem()));
        } else {
            dados.put("erro", true);
        }
        if (cbNumeroJogadores.getSelectedItem().toString().indexOf("Selecione") < 0) {
            dados.put("numeroJogadores", Integer.parseInt((String) cbNumeroJogadores.getSelectedItem()));
        } else {
            dados.put("erro", true);
        }
        return dados;
    }

    public void setCombosBoxes() {
        for (Integer i = 1; i <= (int) controller.get("limitePalavras"); i++) {
            cbNumeroPalavras.addItem(i.toString());
        }
        for (Integer i = 1; i <= (int) controller.get("limiteEtapas"); i++) {
            cbNumeroEtapas.addItem(i.toString());
        }
        for (Integer i = 1; i <= (int) controller.get("limiteJogadores"); i++) {
            cbNumeroJogadores.addItem(i.toString());
        }
        if((Integer)controller.get("numeroEtapas") != 0)
            cbNumeroEtapas.setSelectedItem(controller.get("numeroEtapas"));
        if((Integer)controller.get("numeroPalavras") != 0)
            cbNumeroPalavras.setSelectedItem(controller.get("numeroPalavras"));
        if((Integer)controller.get("numeroJogadores") != 0)
            cbNumeroJogadores.setSelectedItem(controller.get("numeroJogadores"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbNumeroEtapas;
    private javax.swing.JComboBox<String> cbNumeroJogadores;
    private javax.swing.JComboBox<String> cbNumeroPalavras;
    private javax.swing.JCheckBox chbDiferentesCategorias;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbNumeroEtapas;
    private javax.swing.JLabel lbNumeroJogadores;
    private javax.swing.JLabel lbNumeroPalavras;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnDiferentesCategorias;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnNumeroEtapas;
    private javax.swing.JPanel pnNumeroJogadores;
    private javax.swing.JPanel pnNumeroPalavras;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(ControllerAbstrato controller) {
        this.controller = (ControllerConfiguracao) controller;
    }

    @Override
    public JSONObject getDados() {
        return this.controller.getJSON();
    }
}
