/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.ControllerConfiguracao;
import Controllers.ControllerRodaRoda;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;


/**
 *
 * @author raphael
 */
public class ViewMain extends javax.swing.JFrame {
    
    private final Dimension viewInicial = new Dimension(450, 450);
    private final Dimension viewRodaRoda = new Dimension(1000, 450);
    private final Dimension viewConfiguracao = new Dimension(450, 450);
    ViewConfiguracoes vwConf;
    
    /**
     * Creates new form MainFrame
     */
    public ViewMain() {
        initComponents();
        //this.panelCentral.add("viewInicial", new ViewInicial());
        //this.panelCentral.add("viewRodaRoda", new ViewRodaRoda());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }
    
    public ViewMain viewInicial(ControllerRodaRoda controller){
        ViewMain janela = new ViewMain();
        janela.setSize(viewInicial);
        ViewInicial vwInicial = new ViewInicial();
        vwInicial.setController(controller);
        janela.add(vwInicial);
        return janela;
    }
    
    public ViewMain viewRodaRoda(ControllerRodaRoda controller){
        ViewMain janela = new ViewMain();
        janela.setSize(viewRodaRoda);
        ViewRodaRoda vwRodaRoda = new ViewRodaRoda();
        vwRodaRoda.setController(controller);
        janela.add(vwRodaRoda);
        return janela;
    }
    
    public ViewMain viewConfiguracao(ControllerConfiguracao controller){
        ViewMain janela = new ViewMain();
        janela.setSize(viewConfiguracao);
        if(vwConf == null){
        vwConf = new ViewConfiguracoes();
        vwConf.setController(controller);
        }
        vwConf.setCombosBoxes();
        janela.add(vwConf);
        return janela;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
